
console.info('Sacando recetas op...')

onEvent('recipes', event => {
  event.remove({output: 'projecte:condenser_mk1'})
  event.remove({output: 'projecte:transmutation_table'})
  event.remove({output: 'projecte:repair_talisman'})
  event.remove({output: 'projecte:tome'})
  event.remove({output: 'projecte:harvest_goddess_band'})
  event.remove({output: 'projecte:catalytic_lens'})
  event.remove({output: 'projecte:hyperkinetic_lens'})
  event.remove({output: 'projecte:destruction_catalyst'})
  event.remove({output: 'projecte:relay_mk1'})
  event.remove({output: 'mekanism:mekasuit_helmet'})
  event.remove({output: 'mekanism:mekasuit_bodyarmor'})
  event.remove({output: 'mekanism:mekasuit_pants'})
  event.remove({output: 'mekanism:mekasuit_boots'})
  event.remove({output: 'projecte:philosophers_stone'})
  event.remove({output: 'projecte:gem_helmet'})
  event.remove({output: 'projecte:gem_chestplate'})
  event.remove({output:'projecte:gem_leggings'})
  event.remove({output:'projecte:gem_boots'})
  event.remove({output:'mysticalagriculture:infusion_crystal'})
  event.remove({output:'projecte:red_matter'})
  event.remove({output:'botania:terrasteel_helmet'})
  event.remove({output:'botania:terrasteel_chestplate'})
  event.remove({output:'botania:terrasteel_leggings'})
  event.remove({output:'botania:terrasteel_boots'})
  event.remove({output:'mekanism:digital_miner'})
  event.remove({output:'chancecubes:chance_cube'})
  event.remove({output:'mob_grinding_utils:saw'})
  event.remove({output:'mysticalagriculture:supremium_helmet'})
  event.remove({output:'mysticalagriculture:supremium_chestplate'})
  event.remove({output:'mysticalagriculture:supremium_leggings'})
  event.remove({output:'mysticalagriculture:supremium_boots'})
  event.remove({output:'mysticalagriculture:flight_augment'})
  event.remove({output:'avaritia:neutronium_compressor'})
  event.remove({output:'projectex:stone_table'})
  event.remove({output:'projectex:arcane_table'})
  event.remove({output:'torchmaster:megatorch'})
  event.remove({output:'projecte:watch_of_flowing_time'})
  event.remove({output:'projectex:basic_relay'})
  event.remove({output:'projectex:basic_collector'})
  event.remove({output:'projecte:collector_mk1'})
  event.remove({output:'projecte:relay_mk1'})
  event.remove({output:'tiab:timeinabottle'})
  event.remove({output:'tombstone:dust_of_vanishing'})
  event.remove({output: 'securitycraft:mine'})
  event.remove({output: 'projecte:swiftwolf_rending_gale'})
  event.remove({output: 'mmorpg:runeword_station'})
  event.remove({output: 'sons_of_sins:rotten_apple'})
  })