
#General Configs
[general]
	#Range: 0.0 ~ 1000.0
	exp_gain_multi = 5.5
	#Range: 0.0 ~ 1000.0
	vanilla_mob_dmg_as_exile_dmg_at_max_lvl = 1.0
	#Range: 0.0 ~ 1000.0
	ILVL_PER_UPGRADE_LEVEL = 0.5
	start_items = true
	#Range: 0.0 ~ 1000.0
	vanilla_mob_dmg_as_exile_dmg = 1.0
	#Range: 0.0 ~ 1000.0
	party_radius = 200.0
	#Set this to 0 if there is a way to create spawners in the modpack.
	#Range: 0.0 ~ 1000.0
	favor_per_spawner_destroyed = 5.0
	#Range: -1000.0 ~ 1000.0
	MAX_DIFFICULTY = 100.0
	#Range: -1000.0 ~ 1000.0
	DIFFICULTY_PER_HOSTILE_KILL = 0.005
	#This is for modded gear that can't be automatically recognized by the mod. If there's say a weapon like a staff in another mod, but this mod doesn't recognize it. Put it here. The usage is: modid:path:gear_slot_id. Example: minecraft:diamond_sword:sword
	gear_compatibility = ["minecraft:iron_sword:sword"]
	#Range: -1000.0 ~ 1000.0
	DIFFICULTY_PER_SECOND = 5.0E-4
	#Range: 0.0 ~ 1.0
	min_loot_chance = 0.01
	#Range: 0.0 ~ 1000.0
	gem_drop_rate = 0.5
	#Range: 0.0 ~ 100000.0
	MOB_DMG_MULTI_PER_DIFFICULTY = 0.01
	TURN_REQ_ILVL_INTO_RECCOMENDATION = false
	#Range: 0 ~ 100000
	HP_VALUE_NEEDED_FOR_MAX_ENVIRO_DMG_PROTECTION = 125
	#Range: 0.0 ~ 1000.0
	favor_per_chest = 20.0
	#Range: -1000.0 ~ 1000.0
	DIFFICULTY_PER_DEATH = -1.0
	#Range: -1000.0 ~ 1000.0
	DIFFICULTY_PER_INCREASE_ITEM = 10.0
	enable_favor = false
	#Range: 0 ~ 20
	max_uniques_worn = 20
	#Range: 0.0 ~ 1000.0
	extra_mob_stats_per_lvl = 0.02
	#Range: 0.0 ~ 1000.0
	regen_hunger_cost = 10.0
	loot_announcements = true
	#Range: -1000.0 ~ 1000.0
	DIFFICULTY_PER_DECREASE_ITEM = 10.0
	dont_sync_ambient_mob_data = true
	#Range: 0.0 ~ 1.0E7
	max_instability = 1000.0
	scale_mob_to_nearby_player_lvl = false
	#Range: 0.0 ~ 1.0
	MAX_ENVIRO_DMG_PROTECTION_FROM_HP_MULTI = 0.75
	#Range: 0.0 ~ 100000.0
	DEATH_DIFFICULTY_COOLDOWN = 72000.0
	#Range: 0.0 ~ 1000.0
	PLAYER_VANILLA_DMG_MULTI = 0.5
	#Range: 0.0 ~ 1000.0
	ingredient_drop_rate = 5.0
	#Range: 0.0 ~ 1000.0
	rune_drop_rate = 0.05
	all_players_are_allied = false
	#Range: 0 ~ 100000
	starting_favor = 100
	#Range: 0.0 ~ 1000.0
	currency_drop_rate = 0.2
	#Range: -1000 ~ 1000
	MAX_MOB_LVL_HIGHER_THAN_PLAYER_FOR_DIFF = 20
	#Range: 0.0 ~ 1000.0
	pvp_dmg_multi = 1.0
	#Range: 0.0 ~ 1000.0
	gear_drop_rate = 7.0
	require_team_for_dungeons = true
	#Range: 0.0 ~ 1.0
	death_exp_penalty = 0.0
	#Range: 0.0 ~ 100000.0
	MOB_HP_MULTI_PER_DIFFICULTY = 0.0
	#Range: 0.0 ~ 100000.0
	MOB_LOOT_MULTI_PER_DIFFICULTY = 0.01
	#Range: 0.0 ~ 1.0
	lvl_distance_penalty_per_tier = 0.5

