
#Does It Tick Settings
[Settings]

	[Settings."Core Config"]
		"Use Automatic Distance Values (Higher in Singleplayer, Lower in SMP)" = true
		"Use Extreme Measures (quick setting to turn on high-performance mode)" = false
		"Ignore Dead Entities (with this turned on, the tick check will run a lot faster, but entities won't die if outside range)" = true

	[Settings."Custom Tick Distance Settings"]
		"(LivingEntity) Max Horizontal Tick Distance [Default 64]" = 64
		"(LivingEntity) Max Vertical Tick Distance [Default 32]" = 32
		"(LivingEntity) Max Spawn Check Horizontal Distance [Default 64]" = 64
		"(LivingEntity) Max Spawn Check Vertical Distance [Default 32]" = 32
		"(Fluid) Max Fluid Tick Horizontal Distance [Squared, Default 64]" = 64
		"(Fluid) Max Fluid Tick Vertical Distance [Default 32]" = 32

	[Settings."Other Settings"]
		"Optimize Item Movement (items move at 1/4 speed)" = false
		"Optimize Fluid Ticks" = false
		"Ignore Dead Entities (with this turned on, the tick check will run a lot faster, but entities won't die if outside range)" = true

	[Settings."Entity Whitelist"]
		"Whitelisted Entities" = ["minecraft:ender_dragon", "minecraft:ghast", "minecraft:wither", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "alexsmobs:spectre", "twilightforest:naga", "twilightforest:lich", "twilightforest:yeti", "twilightforest:snow_queen", "twilightforest:minoshroom", "twilightforest:hydra", "twilightforest:knight_phantom", "twilightforest:ur_ghast", "mowziesmobs:barako", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "mowziesmobs:naga", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:dragon_multipart"]

