onEvent('jei.hide.items', event => {
    event.hide('avaritia:extremecraftingtable')
    event.hide('avaritia:neutronium_compressor')
    event.hide('avaritia:iron_singularity')
    event.hide('avaritia:golden_singularity')
    event.hide('avaritia:lapis_singularity')
    event.hide('avaritia:redstone_singularity')
    event.hide('avaritia:nether_quartz_singularity')
    event.hide('avaritia:diamond_singularity')
    event.hide('avaritia:emerald_singularity')
    event.hide('avaritia:neutron_collector')
    event.hide('avaritia:gold_singularity')
    event.hide(Item.of('avaritia:skullfire_sword', '{Damage:0,AS_Amulet_Holder:[I;-1589857818,1385778581,-1508201656,-657444428]}'))
    event.hide('mysticalagradditions:creative_essence')
    event.hide('mysticalagriculture:creative_soulium_dagger')
    event.hide('rftoolspower:dimensionalcell_creative')
    event.hide('rftoolsutility:creative_screen')
    event.hide('avaritia:gold_singularity')
    event.hide('refinedstorage:creative_portable_grid')
    event.hide('refinedstorage:creative_storage_block')
    event.hide('refinedstorage:creative_fluid_storage_block')
    event.hide('refinedstorage:creative_controller')
    event.hide('refinedstorage:creative_wireless_grid')
    event.hide('refinedstorage:creative_wireless_fluid_grid')
    event.hide('refinedstorage:creative_wireless_crafting_monitor')
    event.hide('refinedstorage:white_creative_controller')
    event.hide('refinedstorage:orange_creative_controller')
    event.hide('refinedstorage:magenta_creative_controller')
    event.hide('refinedstorage:yellow_creative_controller')
    event.hide('refinedstorage:lime_creative_controller')
    event.hide('refinedstorage:pink_creative_controller')
    event.hide('refinedstorage:gray_creative_controller')
    event.hide('refinedstorage:light_gray_creative_controller')
    event.hide('refinedstorage:cyan_creative_controller')
    event.hide('refinedstorage:purple_creative_controller')
    event.hide('refinedstorage:blue_creative_controller')
    event.hide('refinedstorage:brown_creative_controller')
    event.hide('refinedstorage:green_creative_controller')
    event.hide('refinedstorage:red_creative_controller')
    event.hide('refinedstorage:black_creative_controller')
    event.hide('thermal:fluid_tank_creative_augment')
    event.hide('thermal:machine_catalyst_creative_augment')
    event.hide('tconstruct:creative_slot')
    event.hide(Item.of('tconstruct:creative_slot', '{slot:"upgrades"}'))
    event.hide(Item.of('tconstruct:creative_slot', '{slot:"abilities"}'))
    event.hide(Item.of('tconstruct:creative_slot', '{slot:"defense"}'))
    event.hide(Item.of('tconstruct:creative_slot', '{slot:"souls"}'))
    event.hide('rats:rat_upgrade_creative')
    event.hide('rats:creative_cheese')
    event.hide('rats:rat_upgrade_combined_creative')
    event.hide('immersiveengineering:capacitor_creative')
    event.hide('create:creative_fluid_tank')
    event.hide('create:creative_crate')
    event.hide('create:handheld_worldshaper')
    event.hide('iceandfire:creative_dragon_meal')
    event.hide('mekanism:creative_bin')
    event.hide('evilcraft:creative_blood_drop')
    event.hide('refinedstorageaddons:creative_wireless_crafting_grid')
    event.hide('botania:lens_storm')
    event.hide(Item.of('botania:mana_tablet', '{mana:500000,creative:1b}'))
    event.hide('chancecubes:creative_pendant')
    event.hide('botania:infrangible_platform')
    event.hide('mowziesmobs:earth_talisman')
    event.hide('mowziesmobs:earthbore_gauntlet')
    event.hide('refinedstorage:creative_fluid_storage_disk')
    event.hide('refinedstorage:creative_fluid_storage_disk')
    event.hide('mmorpg:runeword_station')
    event.hide('mmorpg:portal')
    event.hide('mmorpg:teleporter')
    event.hide('mmorpg:identify_tome')
    event.hide('mmorpg:potions/reset_all_perks')
    event.hide('mmorpg:custom_crate')
    event.hide('projecte:repair_talisman')
  })